version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: blog_api_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_api_dev
    ports:
      - "5433:5432"
    volumes:
      - "./db_data:/var/lib/postgresql/data/"
